Add GH Actions and docs on tests.

diff --git a/.github/workflows/development.yaml b/.github/workflows/development.yaml
--- a/.github/workflows/development.yaml
+++ b/.github/workflows/development.yaml
@@ -1,36 +1,134 @@
-# This is a basic workflow to help you get started with Actions
-
-name: CI
-
-# Controls when the action will run. 
+name: Development
 on:
-  # Triggers the workflow on push or pull request events but only for the master branch
   push:
-    branches: [ master ]
   pull_request:
-    branches: [ master ]
-
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
-
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
   build:
-    # The type of runner that the job will run on
     runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
+    strategy:
+      matrix:
+        include:
+          - py_ver: 3.8
+            distro: alpine
+            image: djbase
+    env:
+      PY_VER: ${{matrix.py_ver}}
+      DISTRO: ${{matrix.distro}}
+      IMAGE: ${{matrix.image}}
+      HOST_UID: "1001"
+      DOCKER_CLIENT_TIMEOUT: "120"
+      COMPOSE_HTTP_TIMEOUT: "120"
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
-
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: Compile image
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          DJGUI_API_VERSION=$(cat dj_gui_api_server/version.py | tail -1 | \
+            awk -F\' '{print $2}')
+          docker-compose -f LNX-docker-compose.yaml build
+          IMAGE=$(docker images --filter "reference=datajoint/*" --format "{{.Repository}}")
+          TAG=$(docker images --filter "reference=datajoint/*" --format "{{.Tag}}")
+          docker save "${IMAGE}:${TAG}" | gzip > "djgui_api-py${PY_VER}-${DISTRO}.tar.gz"
+      - name: Add image artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: ${{format('{0}-py{1}-{2}', 'djgui_api', matrix.py_ver, matrix.distro)}}
+          path: >
+            ${{format('{0}-py{1}-{2}.tar.gz', 'djgui_api', matrix.py_ver, matrix.distro)}}
+          retention-days: 1
+  test:
+    needs: build
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        include:
+          - py_ver: 3.8
+            distro: alpine
+            image: djbase
+    env:
+      PY_VER: ${{matrix.py_ver}}
+      DISTRO: ${{matrix.distro}}
+      IMAGE: ${{matrix.image}}
+      HOST_UID: "1001"
+      DOCKER_CLIENT_TIMEOUT: "120"
+      COMPOSE_HTTP_TIMEOUT: "120"
+    steps:
+      - name: Fetch image artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: ${{format('{0}-py{1}-{2}','djgui_api', matrix.py_ver, matrix.distro)}}
+      - name: Verify image
+        run: |
+          docker load < "djgui_api-py${PY_VER}-${DISTRO}.tar.gz"
+          DJGUI_API_VERSION=$(cat dj_gui_api_server/version.py | tail -1 | \
+            awk -F\' '{print $2}')
+          docker-compose -f LNX-docker-compose.yaml up --build --exit-code-from app
+  # publish:
+  #   if: github.event_name == 'push' && github.ref == 'refs/heads/master'
+  #   needs: test
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     matrix:
+  #       include:
+  #         - py_ver: 3.8
+  #           distro: alpine
+  #           image: djbase
+  #   env:
+  #     PY_VER: ${{matrix.py_ver}}
+  #     DISTRO: ${{matrix.distro}}
+  #     IMAGE: ${{matrix.image}}
+  #     DOCKER_USERNAME: ${{secrets.docker_username}}
+  #     DOCKER_PASSWORD: ${{secrets.docker_password}}
+  #   steps:
+  #     - name: Fetch image artifact
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         name: ${{format('{0}-py{1}-{2}', matrix.conda_ver, matrix.py_ver, matrix.distro)}}
+  #     - name: Publish image
+  #       run: |
+  #         echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
+  #         docker load < "${CONDA_VER}-py${PY_VER}-${DISTRO}.tar.gz"
+  #         IMAGE=$(docker images --filter "reference=datajoint/*" --format "{{.Repository}}")
+  #         TAG=$(docker images --filter "reference=datajoint/*" --format "{{.Tag}}")
+  #         docker push "${IMAGE}:${TAG}"
+  #         docker tag "${IMAGE}:${TAG}" "${IMAGE}:${TAG}-${GITHUB_SHA:0:7}"
+  #         docker push "${IMAGE}:${TAG}-${GITHUB_SHA:0:7}"
+  #         [ "$PY_VER" == "3.9" ] && [ "$DISTRO" == "debian" ] \
+  #                 && docker tag "${IMAGE}:${TAG}" "${IMAGE}:latest" \
+  #                 && docker push "${IMAGE}:latest" \
+  #             || echo "skipping 'latest' tag..."
+  # publish-docs:
+  #   if: github.event_name == 'push' && github.ref == 'refs/heads/master'
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v1
+  #     - name: Build docs
+  #       uses: ammaraskar/sphinx-action@master
+  #       with:
+  #         docs-folder: "docs/"
+  #     # - name: Upload docs artifact
+  #     #   uses: actions/upload-artifact@v1
+  #     #   with:
+  #     #     name: docs-html
+  #     #     path: docs/_build/html/
+  #     #     retention-days: 1
+  #     - name: Commit documentation changes
+  #       run: |
+  #         git clone https://github.com/${GITHUB_REPOSITORY}.git \
+  #             --branch gh-pages --single-branch gh-pages
+  #         rm -R gh-pages/*
+  #         cp -r docs/_build/html/* gh-pages/
+  #         cp .gitignore gh-pages/
+  #         touch gh-pages/.nojekyll
+  #         cd gh-pages
+  #         git config --local user.email "action@github.com"
+  #         git config --local user.name "GitHub Action"
+  #         git add . --all
+  #         git commit -m "Update documentation" -a || true
+  #         # The above command will fail if no changes were present, so we ignore
+  #         # the return code.
+  #     - name: Push changes
+  #       uses: ad-m/github-push-action@master
+  #       with:
+  #         branch: gh-pages
+  #         directory: gh-pages
+  #         github_token: ${{secrets.GITHUB_TOKEN}}
